###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://www.ory.com/docs/hydra/5min-tutorial                            #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################
services:
  mock-ui:
    build: .
    container_name: mock-ui
    ports:
      - "3000:3000"
    environment:
      - LDAP_URI=${LDAP_URI:-ldaps://20.197.49.160:636}
      - LDAP_SKIP_TLS_VERIFY=${LDAP_SKIP_TLS_VERIFY:-true}
      - LDAP_BASE_DN=${LDAP_BASE_DN:-DC=lab,DC=local}
      - LDAP_BIND_DN=${LDAP_BIND_DN:-user1@lab.local}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD:-adminpassword}
      - LDAP_USER_SEARCH_BASE=${LDAP_USER_SEARCH_BASE:-DC=lab,DC=local}
      - LDAP_USERNAME_ATTRIBUTE=${LDAP_USERNAME_ATTRIBUTE:-sAMAccountName}
      - LDAP_RDN_ATTRIBUTE=${LDAP_RDN_ATTRIBUTE:-cn}
      - LDAP_UUID_ATTRIBUTE=${LDAP_UUID_ATTRIBUTE:-objectGUID}
      - LDAP_USER_OBJECT_CLASS=${LDAP_USER_OBJECT_CLASS:-user}
      - LDAP_SEARCH_SCOPE=${LDAP_SEARCH_SCOPE:-LEVEL}
      - LDAP_USER_FILTER=${LDAP_USER_FILTER:-}
      - LDAP_UPN_SUFFIX=${LDAP_UPN_SUFFIX:-lab.local}
    restart: always
    networks:
      - netsec-bridge
  sqlite:
    image: busybox
    volumes:
      - hydra-sqlite:/mnt/sqlite
    command: "chmod -R 777 /mnt/sqlite"
  hydra:
    # image: oryd/hydra:v25.4.0
    # build:
    #   context: .
    #   dockerfile: .docker/Dockerfile-local-build
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - hydra-sqlite:/mnt/sqlite:rw
      - type: bind
        source: ./config
        target: /etc/config/hydra
    # pull_policy: missing
    environment:
      - DSN=sqlite:///mnt/sqlite/db.sqlite?_fk=true&mode=rwc
    restart: unless-stopped
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
    networks:
      - intranet
      - netsec-bridge
    image: oryd/hydra:v26.2.0
  hydra-migrate:
    # image: oryd/hydra:v25.4.0
    # build:
    #   context: .
    #   dockerfile: .docker/Dockerfile-local-build
    environment:
      - DSN=sqlite:///mnt/sqlite/db.sqlite?_fk=true&mode=rwc
    command: migrate -c /etc/config/hydra/hydra.yml sql up -e --yes
    # pull_policy: missing
    volumes:
      - hydra-sqlite:/mnt/sqlite:rw
      - type: bind
        source: ./config
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet
    depends_on:
      sqlite:
        condition: service_completed_successfully
    image: oryd/hydra:v26.2.0

networks:
  intranet:
  netsec-bridge:
    external: true
volumes:
  hydra-sqlite: